### ISSUE TITLE
nimbase.h

### ISSUE THREAD

**Issue by ponyatov** [yglukhov/android#7]
I tried to use this module with Android NDK, and faced with a problem -- there is no `nimbase.h` in my `~/.nimble`.

I've opened topic here: https://forum.nim-lang.org/t/5156

Maybe some special procedure must be conducted especially for this `android` package?
(downloading `/include` from some specific space, defining `-Dsomething` in NDK build, etc)

**Comment by yglukhov** [comment]
It's a matter of how you do the build, and not related to this library. If you're using naketools from nimx, file a corresponding issue in nimx tracker. If you're using some ndk-build, just pass the needed header search paths.
